### ISSUE TITLE
Allow QRCode rendering as Overlay

### ISSUE THREAD

**Issue by DavidArayan** [Plattar/plattar-ar-adapter#60]
## About

The current QRCode rendering performed as part of the `<plattar-embed />` node requires removing the 3D viewer from the DOM and pushing the QRCode Renderer to the DOM. 

This creates the following issues/concerns.

1. The Viewer State is not maintained. This means when the QRCode rendering is no longer required, the Viewer must be re-initialised/loaded leading to poor user experience.
2. Messenger interfaces for performing variation switching, configuration switching or other functionality is not available in the QRCode Renderer.

## Proposal

We propose changing the way QRCode's are rendered as part of the `<plattar-embed />` node. Instead of replacing the 3D Renderer, the QRCode should simply render on top of the existing Renderer. Simple methods should be introduced for `showing`, `hiding` and `refreshing` the QRCode based on the current state of the renderer/embed attributes.

**New Functions**

The following functions will be made available to the `plattar-embed` interface.

- `showQRCode() : Promise<void>` - Display the appropriate QRCode based on the state of the current attributes
- `hideQRCode() : Promise<void>` - Hide a previously displayed QRCode
- `refreshQRCode() : Promise<void>` - Refresh the QRCode to take into account the current/updated attribute state. This will happen automatically for most attributes.

**Usage Example**

Given the following `<plattar-embed />` node

```html
<plattar-embed id="embed" scene-id="" embed-type="configurator" show-ar="true" init="viewer"></plattar-embed>
```
New functions can be accessed as follows

```javascript
const embed = document.getElementById("embed");

embed.showQRCode();
embed.hideQRCode();
embed.refreshQRCode();
```

## Existing Interfaces

The existing functionality as noted below will continue to function in the same way as previously, ensuring previous integrations relying on those functions will not break.

- `startQRCode()` - Code Reference [plattar-embed.ts L147](https://github.com/Plattar/plattar-ar-adapter/blob/main/plattar-ar-adapter/src/embed/plattar-embed.ts#L147) - this will call the new `showQRCode()` function
- `removeRenderer()` - Code Reference [plattar-embed.ts L162](https://github.com/Plattar/plattar-ar-adapter/blob/main/plattar-ar-adapter/src/embed/plattar-embed.ts#L162) - this will remove the QRCode (if currently visible) by calling the new `hideQRCode()` function, otherwise it will remove the Renderer. To remove both, will need to call twice.

## Changes to existing Integrations

The following changes will apply to existing integrations.

1. `removeRenderer()` will no longer remove the 3D Renderer if the QRCode is currently rendering (will need to call it twice)

## Tasks

- [x] - Gather feedback concerning the backwards incompatible changes
- [x] - Development of the feature (and attach PR)
- [ ] - Testing, including regression testing against existing examples at [https://docs.plattar.com](https://docs.plattar.com)
- [ ] - Add Documentation via [https://docs.plattar.com](https://docs.plattar.com) to highlight new features/interfaces
- [ ] - Accept/Merge the PR Request

**Comment by DavidArayan** [comment]
Closing due to inactivity
