### ISSUE TITLE
Implement AR Callbacks

### ISSUE THREAD

**Issue by DavidArayan** [Plattar/plattar-ar-adapter#61]
## About

IOS and Android AR contains the ability to display a simple UI/UX and an actionable Button to perform callbacks/additional functionality when clicked. This proposal implements those details and allows registering a callback for listening to the actionable button.

~~This feature will be `enabled` permanently and cannot be disabled!~~
This feature can be enabled via two different options

1. Set the `show-ar-banner` attribute to `true` in the `<plattar-embed />` node (defaults to `false`)
2. Use the `arclick` callback which automatically sets the `show-ar-banner` to `true` when used

## Screenshots

IOS and Android UI/UX for filling in the `title`, `subtitle` and `button`

<p float="left">
<img width="200" alt="Screenshot" src="https://user-images.githubusercontent.com/7587896/227823969-51b4c141-cf23-499e-a7f3-c3910005aba5.png">
<img width="200" alt="Screenshot" src="https://user-images.githubusercontent.com/7587896/227823998-32528fae-799f-4256-923d-3e67f4385088.png">
</p>

## Variables and Constraints

- `title` - defaults to `project.title` ~~or can be overridden in the Plattar CMS Scene Editor~~
- `subtitle` - defaults `scene.title` ~~or can be overridden in the Plattar CMS Scene Editor~~
- `button` - defaults to `Visit` and cannot be changed
- ~~`url` - defaults to `location.href` or can be overridden in the Plattar CMS Scene Editor~~ URL/Navigation to other pages should be done via the callback function itself

## Callback Functionality

The `<plattar-embed />` will contain a new callback functionality that executes whenever the `Visit` button is tapped on either Android or IOS.

The two new functions are as follows

**addEventListener(string:event, callback:Function): void**

Adds a new Event Listener to the SDK. The Event to listen for when the `Visit` button is clicked is named `arclick`.

```javascript
const callback = () => {
    // do something when AR Button is clicked
};

embed.addEventListener(`arclick`, callback);
```

**removeEventListener(string:event, callback:Function): void**

Removes a previously added Event Listener from the SDK.

```javascript
const callback = () => {
    // do something when AR Button is clicked
};

embed.removeEventListener(`arclick`, callback);
```

## Tasks

- [x] - Gather comments regarding the proposal
- [x] - Implementation and open Pull Request
- [x] - Solution Testing/Regression Testing
- [x] - Team Signoff on UI/UX
- [x] - Write examples/docs for `https://docs.plattar.com`
- [x] - Merge PR

**Comment by calrk** [comment]
looks good, im not sure about the priority of this now though.

**Comment by DavidArayan** [comment]
## UI Results for Android & IOS

<p float="left">
  <img src="https://github.com/Plattar/plattar-ar-adapter/assets/7587896/079c7adc-12d7-4a84-90c9-69931292aca6" width="200" />
  <img src="https://github.com/Plattar/plattar-ar-adapter/assets/7587896/a88e61bf-bdda-43c3-9025-2472a4be68f4" width="200" /> 
</p>

## Variables

- `SceneAR` - `title` is **application title** `subtitle` is **scene title**
- `ConfiguratorAR` - `title` is **application title** `subtitle` is **scene title**
- `ModelAR` - `title` is **application title** `subtitle` is **model title**
- `ProductAR` - `title` is **product title** `subtitle` is **variation title**

## Differences between IOS and Android

1. The Button Text can be changed on IOS but not on Android. We opted for `Visit` to maintain consistency
2. The URL Display on IOS is the current model url (which is a Plattar CDN) but for Android its the current page URL. this cannot be changed.
3. (technical) the implementation of callbacks is different for IOS and Android. For Android the page needs to refresh for the callback to occur whilst for IOS there is a direct callback into JavaScript. We opted for both platforms to refresh the page for consistency. This means when AR button is clicked, there will be state loss on the embeds.
4. The screenshot button for IOS VTO when Banners are enabled will no longer show.

<p float="left">
<img width="250" alt="Screenshot 2023-11-28 at 12 37 48 pm" src="https://github.com/Plattar/plattar-ar-adapter/assets/7587896/e97564b0-a853-49d6-a017-e4e308385006">
<img width="250" alt="Screenshot 2023-11-28 at 12 38 02 pm" src="https://github.com/Plattar/plattar-ar-adapter/assets/7587896/809eef72-4ba4-4d9b-805c-5c664edf987c">
</p>
