### ISSUE TITLE
Allow AR Banner customisation via attributes

### ISSUE THREAD

**Issue by DavidArayan** [Plattar/plattar-ar-adapter#73]
## About

This is an extension of the work done in [Issue 61](https://github.com/Plattar/plattar-ar-adapter/issues/61) that will allow customising the AR Banners via attributes.

## Proposal

The following attributes will be made customisable.

- Title via `ar-banner-title` - defaults to previous default values if not set (depends on AR type)
- Subtitle via `ar-banner-subtitle` - defaults to previous default if not set (depends on AR type)
- CTA Button via `ar-banner-button` - defaults to `Visit` if not set. Has no effect on Android (cannot be modified)

## Examples

Setting a title

```html
<plattar-embed ar-banner-title="my title" />
```

Setting a subtitle

```html
<plattar-embed ar-banner-subtitle="my title" />
```

Setting CTA button name

```html
<plattar-embed ar-banner-button="Buy Now" />
```

## Tasks

- [x] - Gather comments regarding the proposal
- [x] - Implementation and open Pull Request
- [ ] - Solution Testing/Regression Testing
- [ ] - Write examples/docs for `https://docs.plattar.com`
- [ ] - Merge PR

**Comment by DavidArayan** [comment]
Closing due to inactivity
